apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
spec:
  template:
    spec:
      containers:
        - name: dispatcher-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9003
            initialDelaySeconds: 100
            periodSeconds: 50
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9003
            initialDelaySeconds: 50
            periodSeconds: 150