apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/prana12/cn-catalog-service/k8s?ref=6c525f9f5474dca90ed1be51486d499bd12856c8

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/prana12/catalog-service
  newTag: 6c525f9f5474dca90ed1be51486d499bd12856c8

replicas:
- count: 2
  name: catalog-service
