apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/prana12/cn-order-service/k8s?ref=9b8d6c2b7fa23389a4f2feb930c779ba7dcf7d43

patchesStrategicMerge:
  - patch-env.yml
  - patch-resources.yml
  - patch-volumes.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: order-config

images:
  - name: order-service
    newName: ghcr.io/prana12/order-service
    newTag: 9b8d6c2b7fa23389a4f2feb930c779ba7dcf7d43

replicas:
  - count: 1
    name: order-service